openapi: 3.0.0
info:
  title: Password Management API
  version: 1.0.0
  description: API для управления паролями, включает операции CRUD

paths:
  /api/passwords:
    post:
      summary: Создать новый пароль
      operationId: createPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                site:
                  type: string
                  example: "example.com"
                username:
                  type: string
                  example: "user1"
                password:
                  type: string
                  example: "securePass123"
      responses:
        '201':
          description: Пароль успешно создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  site:
                    type: string
                    example: "example.com"
                  username:
                    type: string
                    example: "user1"
                  password:
                    type: string
                    example: "securePass123"

    get:
      summary: Получить список всех паролей
      operationId: listPasswords
      responses:
        '200':
          description: Список паролей
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    site:
                      type: string
                      example: "example.com"
                    username:
                      type: string
                      example: "user1"
                    password:
                      type: string
                      example: "securePass123"

  /api/passwords/{id}:
    get:
      summary: Получить один пароль по ID
      operationId: getPassword
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Информация о пароле
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  site:
                    type: string
                    example: "example.com"
                  username:
                    type: string
                    example: "user1"
                  password:
                    type: string
                    example: "securePass123"

    put:
      summary: Обновить пароль по ID
      operationId: updatePassword
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                site:
                  type: string
                  example: "example.com"
                username:
                  type: string
                  example: "user1"
                password:
                  type: string
                  example: "newSecurePass456"
      responses:
        '200':
          description: Пароль успешно обновлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  site:
                    type: string
                    example: "example.com"
                  username:
                    type: string
                    example: "user1"
                  password:
                    type: string
                    example: "newSecurePass456"

    delete:
      summary: Удалить пароль по ID
      operationId: deletePassword
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Пароль успешно удален, содержимого нет
