openapi: 3.0.0
info:
  title: Password Management API
  version: 1.0.0
  description: API для управления паролями, включает операции CRUD

tags:
  - name: Passwords
    description: Операции для управления паролями

paths:
  /api/passwords:
    post:
      tags:
        - Passwords
      summary: Создать новый пароль
      operationId: createPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordRequest'
      responses:
        '201':
          description: Пароль успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResponse'

    get:
      tags:
        - Passwords
      summary: Получить список всех паролей
      operationId: listPasswords
      responses:
        '200':
          description: Список паролей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PasswordResponse'

  /api/passwords/{id}:
    get:
      tags:
        - Passwords
      summary: Получить один пароль по ID
      operationId: getPassword
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Информация о пароле
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResponse'

    put:
      tags:
        - Passwords
      summary: Обновить пароль по ID
      operationId: updatePassword
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordRequest'
      responses:
        '200':
          description: Пароль успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResponse'

    delete:
      tags:
        - Passwords
      summary: Удалить пароль по ID
      operationId: deletePassword
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Пароль успешно удален

components:
  schemas:
    PasswordRequest:
      type: object
      required:
        - site
        - username
        - password
      properties:
        site:
          type: string
          example: "example.com"
        username:
          type: string
          example: "user1"
        password:
          type: string
          example: "securePass123"

    PasswordResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        site:
          type: string
          example: "example.com"
        username:
          type: string
          example: "user1"
        password:
          type: string
          example: "securePass123"
